// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Windows;

namespace WpfLinuxSdkCheck
{
    /// <summary>
    ///  Code-behind for the compiled-XAML window. The partial class and InitializeComponent are
    ///  generated by the markup compiler, so this file compiling at all is part of the test.
    /// </summary>
    public partial class XamlWindow : Window
    {
        public XamlWindow()
        {
            InitializeComponent();
        }

        private void OnClick(object sender, RoutedEventArgs e)
        {
            Status.Text = "clicked";
        }

        /// <summary>Report what the markup actually produced, for the unattended check.</summary>
        internal string Describe() =>
            $"heading='{Heading.Text}' headingSize={Heading.FontSize} " +
            $"styledBrush={Heading.Foreground} " +
            $"templated={Go.Template != null} " +
            $"boundText='{Input.Text}' status='{Status.Text}'";
    }
}
