// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

//
// The test host's entry point, written out rather than auto-generated, for one reason: macOS.
//
// These tests need a REAL top-level Window (a PresentationSource is what the inspector walks), and AppKit will only build one on the PROCESS MAIN
// THREAD -- which a test runner does not run tests on. So the main thread keeps the UI and the
// runner moves beside it, the arrangement Wpf.Input.Tests and Wpf.Platform.Tests both use.
//
// Mirrors obj/.../XunitAutoGeneratedEntryPoint.cs; keep RunTests in step with it if xunit's
// generated shape changes. SelfRegisteredExtensions is still generated for us.
//

using System;
using System.Linq;
using System.Threading;
using System.Windows.Threading;
using Wpf.DevTools.Tests;

internal static class Program
{
    public static int Main(string[] args)
    {
        if (!OperatingSystem.IsMacOS())
        {
            return RunTests(args);
        }

        // Claim AppKit's event system for the main thread before the runner exists.
        //
        // -_DPSNextEvent builds the process's event queue inside a dispatch_once whose first act is
        // to assert that it is building the MAIN thread's. The assert is a __builtin_trap, so losing
        // that race is EXC_BREAKPOINT with no managed stack -- or the CLR's signal handler catches
        // the trap, resumes at the faulting instruction, and the process spins inside AppKit for
        // ever. An application never meets it because its main thread is in the event loop before it
        // does anything else; a test host is the opposite, so the claim is made explicitly here.
        // Wpf.Platform.Tests carries the same two lines and the longer version of this note.
        MS.Internal.Interop.CocoaWindow.EnsureApplication();
        MS.Internal.Interop.CocoaWindow.PumpEvents(0);

        Dispatcher main = Dispatcher.CurrentDispatcher;
        UiThread.UseDispatcher(main);

        int exitCode = 0;
        var runner = new Thread(() =>
        {
            try
            {
                exitCode = RunTests(args);
            }
            finally
            {
                // Whatever happened, stop pumping or the process never exits.
                main.InvokeShutdown();
            }
        })
        {
            IsBackground = false,
            Name = "xunit test runner",
        };

        runner.Start();
        Dispatcher.Run();
        runner.Join();

        return exitCode;
    }

    private static int RunTests(string[] args)
        => args.Any(arg => arg == "-automated" || arg == "@@")
            ? Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
            // SelfRegisteredExtensions is generated by Microsoft.Testing.Platform.MSBuild, which is a
            // different generator from xunit's entry point and still runs. Registering it is not
            // optional: it is what installs the MSBuild integration, and without it `dotnet test`
            // dies on its own argument -- "Unknown option '--internal-msbuild-node'".
            : Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(
                  args, SelfRegisteredExtensions.AddSelfRegisteredExtensions)
              .GetAwaiter().GetResult();
}
