// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

//
// The test host's entry point, written out rather than auto-generated, for one reason: macOS.
//
// AppKit will only create a window on the PROCESS MAIN THREAD, and a test runner does not run tests
// there -- xunit dispatches every test onto a worker. This suite drives the windowing heads
// directly, so on macOS the 17 tests that need a window skipped, every run, with
//
//     AppKit windows require the process main thread, which the test runner does not provide
//
// which is a true statement about the HOST and no statement at all about the head. The macOS
// windowing head therefore had no coverage on macOS.
//
// The fix is the arrangement every macOS UI host uses, and the one Wpf.Input.Tests already uses
// beside this project: keep the main thread for the UI and run everything else next to it. The
// tests move to a worker thread, the main thread pumps a Dispatcher, and PlatformThread.InvokeOnMain
// marshals the AppKit work back onto it. Windows and Linux impose no such rule, so there this stays
// out of the way entirely and the generated behaviour is kept exactly.
//
// Mirrors obj/.../XunitAutoGeneratedEntryPoint.cs; keep RunTests in step with it if xunit's
// generated shape changes. SelfRegisteredExtensions is still generated for us.
//

using System;
using System.Linq;
using System.Threading;
using System.Windows.Threading;
using Wpf.Platform.Tests;

internal static class Program
{
    public static int Main(string[] args)
    {
        if (!OperatingSystem.IsMacOS())
        {
            return RunTests(args);
        }

        // Claim AppKit's event system for the main thread BEFORE anything else can touch it.
        //
        // -_DPSNextEvent builds the process's event queue inside a dispatch_once, and the first thing
        // that block does is assert that the queue it is building IS the main thread's:
        // ___NSAssertMainEventQueueIsCurrentEventQueue. The assert is a __builtin_trap, so failing it
        // is EXC_BREAKPOINT with no managed stack -- or, worse, the CLR's signal handler catches the
        // trap, resumes at the faulting instruction and the process spins inside AppKit for ever.
        //
        // An application never sees this: its main thread is inside the event loop before it does
        // anything else. A test host is the opposite -- ninety-odd tests poke the clipboard, the text
        // input context and the rest from xunit's worker threads before any test asks for a window --
        // so which thread reached AppKit's event system first came down to scheduling, and the run
        // passed, spun or trapped accordingly. That is what made this suite fail about one run in
        // three with no test to blame: the same test, the same assertions, a different order.
        //
        // (Which worker-thread call sets up the rival queue was never pinned down, and does not need
        // to be: no test class reproduces it alone, and the main thread getting there first makes the
        // question moot. Sixteen consecutive clean runs, against three failures in the previous nine.)
        //
        // One pump here settles it before the runner exists. PumpEvents(0) blocks for nothing; all it
        // does is run that dispatch_once on the right thread.
        MS.Internal.Interop.CocoaWindow.EnsureApplication();
        MS.Internal.Interop.CocoaWindow.PumpEvents(0);

        // The main thread becomes the UI thread. Dispatcher.CurrentDispatcher creates it for this
        // thread on first touch, and the tests are told where it is before any of them can ask.
        Dispatcher main = Dispatcher.CurrentDispatcher;
        PlatformThread.MainDispatcher = main;

        int exitCode = 0;
        var runner = new Thread(() =>
        {
            try
            {
                exitCode = RunTests(args);
            }
            finally
            {
                // Whatever happened, stop pumping or the process never exits.
                main.InvokeShutdown();
            }
        })
        {
            IsBackground = false,
            Name = "xunit test runner",
        };

        runner.Start();
        Dispatcher.Run();
        runner.Join();

        return exitCode;
    }

    private static int RunTests(string[] args)
        => args.Any(arg => arg == "-automated" || arg == "@@")
            ? Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
            // SelfRegisteredExtensions is generated by Microsoft.Testing.Platform.MSBuild, which is a
            // different generator from xunit's entry point and still runs. Registering it is not
            // optional: it is what installs the MSBuild integration, and without it `dotnet test`
            // dies on its own argument -- "Unknown option '--internal-msbuild-node'" -- while the
            // apphost run, which passes no such argument, looks perfectly healthy.
            : Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(
                  args, SelfRegisteredExtensions.AddSelfRegisteredExtensions)
              .GetAwaiter().GetResult();
}
