// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

//
// The test host's entry point, written out rather than auto-generated, for one reason: macOS.
//
// AppKit will only create a window on the PROCESS MAIN THREAD and aborts the process otherwise, and
// a test runner does not run tests there -- it runs them on worker threads. So every test in this
// assembly, all of which need a real window, failed on macOS before reaching its first assertion:
//
//     A Cocoa window can only be created on the process's main thread; AppKit aborts the process
//     otherwise. Marshal the call to the main thread (Dispatcher) and retry.
//
// The fix is the arrangement every macOS UI host uses: keep the main thread for the UI and run
// everything else beside it. The tests move to a worker thread, the main thread pumps a Dispatcher,
// and UiThread marshals onto that dispatcher instead of spawning an STA thread of its own. Windows
// and Linux impose no such rule, so there they keep the auto-generated behaviour exactly.
//
// Mirrors obj/.../XunitAutoGeneratedEntryPoint.cs; keep RunTests in step with it if xunit's
// generated shape changes. SelfRegisteredExtensions is still generated for us.
//

using System;
using System.Linq;
using System.Threading;
using System.Windows.Threading;
using Wpf.Input.Tests;

internal static class Program
{
    public static int Main(string[] args)
    {
        if (!OperatingSystem.IsMacOS())
        {
            return RunTests(args);
        }

        // The main thread becomes the UI thread. Dispatcher.CurrentDispatcher creates it for this
        // thread on first touch, and the harness is told to use it before any test can ask for one.
        Dispatcher main = Dispatcher.CurrentDispatcher;
        UiThread.UseDispatcher(main);

        int exitCode = 0;
        var runner = new Thread(() =>
        {
            try
            {
                exitCode = RunTests(args);
            }
            finally
            {
                // Whatever happened, stop pumping or the process never exits.
                main.InvokeShutdown();
            }
        })
        {
            IsBackground = false,
            Name = "xunit test runner",
        };

        runner.Start();
        Dispatcher.Run();
        runner.Join();

        return exitCode;
    }

    private static int RunTests(string[] args)
        => args.Any(arg => arg == "-automated" || arg == "@@")
            ? Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
            // SelfRegisteredExtensions is generated by Microsoft.Testing.Platform.MSBuild, which is a
            // different generator from xunit's entry point and still runs. Registering it is not
            // optional: it is what installs the MSBuild integration, and without it `dotnet test`
            // dies on its own argument -- "Unknown option '--internal-msbuild-node'" -- while the
            // apphost run, which passes no such argument, looks perfectly healthy.
            : Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(
                  args, SelfRegisteredExtensions.AddSelfRegisteredExtensions)
              .GetAwaiter().GetResult();
}
