// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

//
// Decoding files SOMEBODY ELSE encoded.
//
// RoundTripTests pairs each encoder with its decoder, which proves they agree with each other -- and
// two halves written together will happily agree on a shared misreading of the format. These
// fixtures come from PIL/libtiff instead, so the only thing they can agree with is the specification.
//
// That matters most for the flavours this repo's own encoder never writes, and which is where the
// interesting bugs live:
//
//   * TIFF LZW is not GIF LZW (MSB-first packing, early code-width bump). A decoder that reuses the
//     GIF loop gets the first few dozen pixels right and then drifts.
//   * The horizontal predictor, which Photoshop writes by default and our encoder never does.
//   * Sub-byte bit depths, palette colour maps (planar RGB, not interleaved triples) and PackBits.
//   * Interlaced GIF, whose four-pass row order is easy to implement plausibly and wrongly.
//   * Animated GIF, where frames after the first are stored as deltas.
//
// The fixtures are a few hundred bytes each and are regenerated by Fixtures/make_fixtures.py, kept
// beside them so the provenance of every file is in the tree rather than in somebody's memory.
//

using System;
using System.Collections.Generic;
using System.IO;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Xunit;

namespace Wpf.Imaging.Tests
{
    public class ForeignEncoderTests
    {
        // The fixture pattern: four quadrants of an 8x8 image. One probe per quadrant.
        private static readonly (int X, int Y)[] Probes = { (1, 1), (6, 1), (1, 6), (6, 6) };

        private const byte Op = 255;

        /// <summary>Red, green, blue, white in reading order, as BGRA.</summary>
        private static readonly byte[][] Quadrants =
        {
            new byte[] { 0, 0, 255, Op },
            new byte[] { 0, 255, 0, Op },
            new byte[] { 255, 0, 0, Op },
            new byte[] { 255, 255, 255, Op },
        };

        public static TheoryData<string> QuadrantFixtures => new()
        {
            "tiff-none.tif",
            "tiff-lzw.tif",
            "tiff-lzw-predictor.tif",
            "tiff-packbits.tif",
            "tiff-deflate.tif",
            "tiff-palette.tif",
            "gif-plain.gif",
            "gif-interlaced.gif",
        };

        [Theory]
        [MemberData(nameof(QuadrantFixtures))]
        public void ForeignFileDecodesToTheRightQuadrants(string fixture)
        {
            BitmapFrame frame = LoadFirstFrame(fixture);

            Assert.Equal(8, frame.PixelWidth);
            Assert.Equal(8, frame.PixelHeight);

            for (int i = 0; i < Probes.Length; i++)
            {
                AssertPixel(frame, Probes[i].X, Probes[i].Y, Quadrants[i], fixture);
            }
        }

        /// <summary>
        ///  Greyscale: one sample per pixel, and the quadrant colours land on the luminance values
        ///  PIL computed. Checks the single-sample path and the 0..255 scaling together.
        /// </summary>
        [Fact]
        public void GreyscaleTiffDecodes()
        {
            BitmapFrame frame = LoadFirstFrame("tiff-grey.tif");

            foreach ((int x, int y, byte level) in new[] { (1, 1, (byte)76), (6, 1, (byte)150), (1, 6, (byte)29), (6, 6, (byte)255) })
            {
                AssertPixel(frame, x, y, new[] { level, level, level, Op }, "tiff-grey.tif");
            }
        }

        /// <summary>
        ///  Bilevel: one BIT per pixel, so the row is bit-packed and padded to a byte. PIL dithers
        ///  when it reduces to two levels, so the pattern is not the quadrants -- what is being
        ///  checked is that every pixel comes out as pure black or pure white, which a bit-offset
        ///  bug would not manage.
        /// </summary>
        [Fact]
        public void BilevelTiffDecodesToBlackAndWhiteOnly()
        {
            BitmapFrame frame = LoadFirstFrame("tiff-bilevel.tif");
            byte[] pixels = ToBgra(frame);

            for (int i = 0; i < pixels.Length; i += 4)
            {
                bool black = pixels[i] == 0 && pixels[i + 1] == 0 && pixels[i + 2] == 0;
                bool white = pixels[i] == 255 && pixels[i + 1] == 255 && pixels[i + 2] == 255;

                Assert.True(black || white,
                    $"pixel {i / 4} is BGRA({pixels[i]},{pixels[i + 1]},{pixels[i + 2]},{pixels[i + 3]}), "
                    + "which is neither black nor white.");
                Assert.Equal(Op, pixels[i + 3]);
            }
        }

        /// <summary>
        ///  RGBA with ExtraSamples: the alpha sample has to survive at its own value rather than
        ///  being forced opaque or multiplied into the colour.
        /// </summary>
        [Fact]
        public void RgbaTiffKeepsItsAlpha()
        {
            BitmapFrame frame = LoadFirstFrame("tiff-rgba.tif");

            for (int i = 0; i < Probes.Length; i++)
            {
                byte[] expected = { Quadrants[i][0], Quadrants[i][1], Quadrants[i][2], 128 };
                AssertPixel(frame, Probes[i].X, Probes[i].Y, expected, "tiff-rgba.tif");
            }
        }

        [Fact]
        public void ForeignMultiPageTiffKeepsEveryPage()
        {
            BitmapDecoder decoder = Load("tiff-multipage.tif");

            Assert.Equal(3, decoder.Frames.Count);

            byte[][] pages = { Quadrants[0], Quadrants[1], Quadrants[2] };   // red, green, blue
            for (int i = 0; i < pages.Length; i++)
            {
                AssertPixel(decoder.Frames[i], 4, 4, pages[i], $"tiff-multipage.tif page {i}");
            }
        }

        /// <summary>
        ///  An animated GIF's later frames are stored as deltas over a canvas. Every frame here is a
        ///  full-size solid colour, so a decoder that returned raw sub-images rather than composed
        ///  ones would still pass -- what this catches is dropping the frames entirely, which is
        ///  what the decoder did before it existed.
        /// </summary>
        [Fact]
        public void AnimatedGifKeepsEveryFrame()
        {
            BitmapDecoder decoder = Load("gif-animated.gif");

            Assert.Equal(3, decoder.Frames.Count);

            byte[][] frames = { Quadrants[0], Quadrants[1], Quadrants[2] };   // red, green, blue
            for (int i = 0; i < frames.Length; i++)
            {
                AssertPixel(decoder.Frames[i], 4, 4, frames[i], $"gif-animated.gif frame {i}");
            }
        }

        /// <summary>The transparent index has to become a transparent PIXEL, not a black one.</summary>
        [Fact]
        public void TransparentGifDecodesTransparent()
        {
            BitmapFrame frame = LoadFirstFrame("gif-transparent.gif");

            byte[] topLeft = PixelAt(frame, 1, 1);
            Assert.Equal(0, topLeft[3]);

            // The other quadrants are untouched and opaque.
            AssertPixel(frame, 6, 1, Quadrants[1], "gif-transparent.gif");
            AssertPixel(frame, 1, 6, Quadrants[2], "gif-transparent.gif");
            AssertPixel(frame, 6, 6, Quadrants[3], "gif-transparent.gif");
        }

        /// <summary>
        ///  Big-endian TIFF, built here rather than loaded: PIL writes little-endian whatever it is
        ///  asked for, so the MM path needs a file constructed by hand. A 2x1 image, red then green,
        ///  which is enough to catch a byte order read the wrong way round (the width would come
        ///  back as 512 rather than 2).
        /// </summary>
        [Fact]
        public void BigEndianTiffDecodes()
        {
            byte[] tiff = BuildBigEndianTiff();

            using var stream = new MemoryStream(tiff);
            BitmapDecoder decoder = BitmapDecoder.Create(stream, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
            BitmapFrame frame = decoder.Frames[0];

            Assert.Equal(2, frame.PixelWidth);
            Assert.Equal(1, frame.PixelHeight);

            AssertPixel(frame, 0, 0, new byte[] { 0, 0, 255, Op }, "big-endian TIFF");
            AssertPixel(frame, 1, 0, new byte[] { 0, 255, 0, Op }, "big-endian TIFF");
        }

        // ---- helpers ---------------------------------------------------------------------

        private static string FixturePath(string name) =>
            Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

        private static BitmapDecoder Load(string fixture)
        {
            string path = FixturePath(fixture);
            Assert.True(File.Exists(path), $"the fixture {fixture} was not copied to the output directory.");

            using var stream = new MemoryStream(File.ReadAllBytes(path));
            return BitmapDecoder.Create(stream, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
        }

        private static BitmapFrame LoadFirstFrame(string fixture) => Load(fixture).Frames[0];

        private static byte[] ToBgra(BitmapSource source)
        {
            var converted = new FormatConvertedBitmap(source, PixelFormats.Bgra32, null, 0);
            var pixels = new byte[source.PixelWidth * source.PixelHeight * 4];
            converted.CopyPixels(pixels, source.PixelWidth * 4, 0);
            return pixels;
        }

        private static byte[] PixelAt(BitmapSource source, int x, int y)
        {
            var converted = new FormatConvertedBitmap(source, PixelFormats.Bgra32, null, 0);
            var pixel = new byte[4];
            converted.CopyPixels(new System.Windows.Int32Rect(x, y, 1, 1), pixel, 4, 0);
            return pixel;
        }

        private static void AssertPixel(BitmapSource source, int x, int y, IReadOnlyList<byte> expected, string what)
        {
            byte[] actual = PixelAt(source, x, y);

            Assert.True(
                actual[0] == expected[0] && actual[1] == expected[1]
                && actual[2] == expected[2] && actual[3] == expected[3],
                $"{what}: pixel ({x},{y}) is BGRA({actual[0]},{actual[1]},{actual[2]},{actual[3]}), "
                + $"expected BGRA({expected[0]},{expected[1]},{expected[2]},{expected[3]}).");
        }

        /// <summary>A minimal 2x1 RGB big-endian ("MM") uncompressed TIFF.</summary>
        private static byte[] BuildBigEndianTiff()
        {
            const int EntryCount = 8;
            const int HeaderSize = 8;
            int ifdSize = 2 + EntryCount * 12 + 4;

            int bitsPerSampleOffset = HeaderSize + ifdSize;      // 3 SHORTs = 6 bytes
            int pixelOffset = bitsPerSampleOffset + 6;

            var buffer = new byte[pixelOffset + 6];
            int o = 0;

            buffer[o++] = (byte)'M';
            buffer[o++] = (byte)'M';
            WriteU16(buffer, ref o, 42);
            WriteU32(buffer, ref o, HeaderSize);

            WriteU16(buffer, ref o, EntryCount);
            WriteEntry(buffer, ref o, 256, 4, 1, 2);                        // ImageWidth
            WriteEntry(buffer, ref o, 257, 4, 1, 1);                        // ImageLength
            WriteEntry(buffer, ref o, 258, 3, 3, (uint)bitsPerSampleOffset); // BitsPerSample
            WriteEntry(buffer, ref o, 259, 3, 1, 1);                        // Compression: none
            WriteEntry(buffer, ref o, 262, 3, 1, 2);                        // Photometric: RGB
            WriteEntry(buffer, ref o, 273, 4, 1, (uint)pixelOffset);        // StripOffsets
            WriteEntry(buffer, ref o, 277, 3, 1, 3);                        // SamplesPerPixel
            WriteEntry(buffer, ref o, 279, 4, 1, 6);                        // StripByteCounts
            WriteU32(buffer, ref o, 0);                                     // no further IFD

            WriteU16(buffer, ref o, 8);
            WriteU16(buffer, ref o, 8);
            WriteU16(buffer, ref o, 8);

            // Pixels, R G B per sample: red then green.
            buffer[o++] = 255; buffer[o++] = 0; buffer[o++] = 0;
            buffer[o++] = 0; buffer[o++] = 255; buffer[o++] = 0;

            return buffer;
        }

        private static void WriteEntry(byte[] buffer, ref int offset, ushort tag, ushort type, uint count, uint value)
        {
            WriteU16(buffer, ref offset, tag);
            WriteU16(buffer, ref offset, type);
            WriteU32(buffer, ref offset, count);

            // Big-endian: a SHORT that fits inline still occupies the FIRST two bytes of the field.
            if (type == 3 && count == 1)
            {
                WriteU16(buffer, ref offset, (ushort)value);
                WriteU16(buffer, ref offset, 0);
            }
            else
            {
                WriteU32(buffer, ref offset, value);
            }
        }

        private static void WriteU16(byte[] buffer, ref int offset, ushort value)
        {
            buffer[offset++] = (byte)(value >> 8);
            buffer[offset++] = (byte)value;
        }

        private static void WriteU32(byte[] buffer, ref int offset, uint value)
        {
            buffer[offset++] = (byte)(value >> 24);
            buffer[offset++] = (byte)(value >> 16);
            buffer[offset++] = (byte)(value >> 8);
            buffer[offset++] = (byte)value;
        }
    }
}
